# Pytorch

#### Introduction

- Pytorch is an open source machine learning library based on Torch library.
- Pytorch is used for aplications like computer vision and natural language processing.
- Pytorch is developed by Facebook's AI reasearch lab.

###### We will be using torch package which contains data for multi-dimesional tensors and mathematical operations.

###### In this notebook I will be using below mentioned funtions. All the below mentioned functions are present in pytorch, these functions will help us to do easy computations.

1. torch.narrow()
2. torch.as_tensor
3. torch.as_strided()
4. torch.empty()
5. torch.cat()

### Function 1- torch.narrow()

- This function will return a narrow version of the tensor.
- The dimension dim is input from start to start+length.The returned tensor and input tensor share the same underlyign storage.

- ###### Parameters
  1. input(Tensor)- the tensor to narrow
  2. dim(int)- the dimension along which to narrow
  3. start(int)- Starting dimension
  4. lenght(int)- the distance to the ending dimension

In [7]:
import torch

In [25]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

#### Example 1

In [115]:
torch.narrow(x,0,1,2)

tensor([[4, 5, 6],
        [7, 8, 9]])

- In the above example in torch.narrow(x,0,0,2)
- x represents the input tensor
- First 0 represent dimensions along which to narrow - we can think it like 0 as rows and 1 as columns
- Second 0 represent starting dimension that from which dimension to start we can consider each row as dimension in this case (since we give 0 as the first domension i.e rows)
- Third 2 represent the distance to ending dimension i.e from starting dimension to ending the distance we have to mention i.e total dimesions we need

#### Example 2

In [122]:
torch.narrow(x,1,0,2)

tensor([[1, 2],
        [4, 5],
        [7, 8]])

- In the above mentioned case what is happening is it going to the take dimension 1 (think it as columns).
- The second one i.e 0 here indicates zeroth column (because we gave 1 as dimension (columns))
- The distance that it total needs i.e it will should take two rows.

#### Example 3 - breaking example

In [130]:
torch.narrow(x,0,2,1)

tensor([[7, 8, 9]])

- Here in this example I am trying to find zeroth dimension's(row) second index row, but the length it is given as two and since total lenght is 3 it should always be less than 3 or 3 but here it is coming 2+2 as 4 so it will throw an error. 

### Function 2 - torch.as_tensor()

- Converts the data into torch.Tensor.
- If the data is already a Tensor with same dtype and device no copy will performed, otherwise a new tensor will be reutrned with computational graph retained if the data Tensor has requires_grad=True
- Similarly, if the data is an ndarray of the corresponding dtype and the device is the cpu, no copy will be performed.

In [142]:
import numpy as np


array([1, 2, 3])

##### Example-1

In [143]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [140]:
torch.as_tensor(a) 

tensor([1, 2, 3], dtype=torch.int32)

##### Example 2

In [147]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
torch.as_tensor(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

##### Example 3- breaking example

In [155]:
a=np.array([1,2,3,[4,5]])
a

array([1, 2, 3, list([4, 5])], dtype=object)

In [156]:
torch.as_tensor(a)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

- Here we can't give values other than float or integer since I gave a list inide teh array it is treated as an object
- Hence it will throw error.

### Function 3 - torch.ones()

###### Returns a tensor filled with scalar value 1, with the shape defined by the variable argument size.

- #### Parameters 
 1. size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.
 2. out (Tensor, optional) – the output tensor.
 3.  dtype (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, uses a global default (see torch.set_default_tensor_type()).
 4. layout (torch.layout, optional) – the desired layout of returned Tensor. Default: torch.strided.
 5. device (torch.device, optional) – the desired device of returned tensor. Default: if None, uses the current device for the default tensor type (see torch.set_default_tensor_type()). device will be the CPU for CPU tensor types and the current CUDA device for CUDA tensor types.
 6. requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.

####  Example 1

In [183]:
x=torch.ones(4,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


#### Example 2

In [185]:
x=torch.ones(6)
print(x)

tensor([1., 1., 1., 1., 1., 1.])


#### Example 3

In [189]:
torch.ones((2,-1))

RuntimeError: Trying to create tensor with negative dimension -1: [2, -1]

- Here we can never give negative numbers while creating dimensions

### Function 4 - torch.empty()
- Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument size.

#### Example 1

In [199]:
torch.empty(2,3)

tensor([[3.4306e-06, 1.0027e-11, 1.7281e-04],
        [2.5932e-09, 1.3664e+22, 1.6520e-04]])

#### Example 2

In [207]:
torch.empty(2,4,dtype=int)

tensor([[30962724186357876, 31244212048494684, 28429436511125606,
         28710881422737503],
        [32651561162571873, 32370073300107356, 34058961815535732,
         30399782823591982]])

#### Example 3 - breaking example

In [220]:
torch.empty((3,2),dtype=str)  # we cannot five str as dtype here

TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=type), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


### Function 5 - torch.cat()

- Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.
- torch.cat() can be seen as an inverse operation for torch.split() and torch.chunk().

#### Example 1

In [221]:
x=torch.randn(2,3)

In [224]:
torch.cat((x,x),0)

tensor([[-0.8254,  0.0302, -0.0106],
        [ 0.6002, -1.8050,  0.4646],
        [-0.8254,  0.0302, -0.0106],
        [ 0.6002, -1.8050,  0.4646]])

#### Example 2

In [226]:
x=torch.randn(2,3)
x

tensor([[ 0.0284, -0.7722, -0.8775],
        [ 0.8964,  0.0824,  0.2607]])

In [228]:
torch.cat((x,x,x),1)

tensor([[ 0.0284, -0.7722, -0.8775,  0.0284, -0.7722, -0.8775,  0.0284, -0.7722,
         -0.8775],
        [ 0.8964,  0.0824,  0.2607,  0.8964,  0.0824,  0.2607,  0.8964,  0.0824,
          0.2607]])

#### Example 3 - breaking example

In [229]:
torch.cat((x,x,x),2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)