### What is Pytorch?

- Pytorch is a library for processing tensors.'

#### What is a tensor?

- A tensor is a number,vector,matrix or any n-dimensional array.

In [1]:
import torch

In [2]:
### Creating a tensor with a single number
t1=torch.tensor(4.)
print(t1.dtype)
print(t1)

torch.float32
tensor(4.)


In [3]:
## Creating a vector
## A vector is an array or list of numbers.
t2=torch.tensor([1.,2,3,4])
print(t2)
print(t2.dtype)

tensor([1., 2., 3., 4.])
torch.float32


In [4]:
# Matrix

t3=torch.tensor([[5.,6],[7,8],[9,10]])
print(t3)

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [5]:
# 3-dimensional array

t4=torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19]]])
print(t4)

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


### Tensors should have regular shape

- Tensors can have any number of dimensions and different lengths along each dimension. To find the length of each dimension we can use .shape property of a tensor.

In [6]:
print(t1)
t1.shape # t1 is a scalar so no dimension

tensor(4.)


torch.Size([])

In [7]:
print(t2)
t2.shape # indicates how many elements are present in the outermost bracket

tensor([1., 2., 3., 4.])


torch.Size([4])

In [8]:
print(t3)
t3.shape # 3 elements in the outermost array and inside it has two elements each

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [9]:
print(t4)
t4.shape # outermost have two elements and inside teh first sub list we again have two
# inside the innermost sublist have three elements

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

#### Tensor operations and gradients

###### We can combine tensors with usual arithmetic operations

In [10]:
x=torch.tensor(3,)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

In [11]:
y=w*x+b # Y is a tensor by combining all the tensors
print(y)

tensor(17., grad_fn=<AddBackward0>)


What makes pytorch special is that we can automatically compute the derivative of y w.r.t the tensors that have requires_grad set to True. To compute the derivative, we can call the .backward method on our result y.

In [15]:
## Compute derivatives
y.backward() #when we give y.backward() pytorch looks into all the inputs given to y and check which all have requires_grad set to true
#

In [16]:
# Display gradients
# all the .grad will only work after executing y.backward()
print("dy/dx:",x.grad) 
print("dy/dw:",w.grad)
print("dy/db:",b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


- x.grad is none beacuse we have not set requires_grad set to true.
- The grad in w.grad stands for gradient, which is another term for gradient used mainly when delaing with matrices.


#### What is the difference between a tensor and a matrix?

- A Matrix has to have 2 diminesions, a matrix is a special type of tensor.
- A tensor is not a matrix, a tensor can be an array,vector,3 dimensional array etc.


### Interoprability with Numpy

- Numpy is an open source library for mathematical and scientific computing in python.
- It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries.

In [20]:
import numpy as np

x=np.array([[1,2],[3,4.]])
print(x)

[[1. 2.]
 [3. 4.]]


In [21]:
## Converting the numpy array to a torch tensor.

y=torch.from_numpy(x)

In [22]:
print(x.dtype,y.dtype)

float64 torch.float64


In [24]:
z=y.numpy() # converting pytorch tensor to a numpy array
print(z)

[[1. 2.]
 [3. 4.]]
